services:
  thesis:
    build: .
    container_name: thesis
    restart: unless-stopped
    networks:
      - web_network
    deploy:
      resources:
        limits:
          memory: 256M
networks:
  web_network:
    external: true