server {
    listen 80;
    location ~* \.(?:png|jpg|jpeg|gif|svg|ico|webp|css|js|map|woff2?|ttf|otf)$ {
        root /usr/share/nginx/html;
        try_files $uri =404;
        add_header Cache-Control "public, max-age=14400" always;
    }
    location ^~ /admin {
        add_header X-Robots-Tag "noindex, nofollow" always;
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}