export const VOICE_INTENTS = {
  NEXT_STEP: "NEXT_STEP",
  PREVIOUS_STEP: "PREVIOUS_STEP",
  REPEAT_INSTRUCTION: "REPEAT_INSTRUCTION",
  SHOW_MATERIALS: "SHOW_MATERIALS",
  CLOSE_MATERIALS: "CLOSE_MATERIALS",
  SHOW_OVERVIEW: "SHOW_OVERVIEW",
  SEARCH: "SEARCH",
  HELP: "HELP",
  STOP_LISTENING: "STOP_LISTENING",
  GO_TO_STEP: "GO_TO_STEP",
  SCROLL_DOWN: "SCROLL_DOWN",
  SCROLL_UP: "SCROLL_UP",
  PAGE_DOWN: "PAGE_DOWN",
  PAGE_UP: "PAGE_UP",
  SCROLL_TOP: "SCROLL_TOP",
  SCROLL_BOTTOM: "SCROLL_BOTTOM",
  UNKNOWN: "UNKNOWN",
};

export const VOICE_STATES = {
  UNSUPPORTED: "unsupported",
  IDLE: "idle",
  LISTENING: "listening",
  PROCESSING: "processing",
  SUCCESS: "success",
  ERROR: "error",
};
